### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by AhmedAllazem** [ESGF/esgf.github.io#93]
Hi everyone,

I am currently using the ESGF portal to download sets of climate data (temperature, precipitation, etc.) from the CMIP6 project. The problem is sometimes it works, and sometimes it doesn't. I would really appreciate it if someone in this area of expertise could help with this.

**Comment by sashakames** [comment]
Hello, please see https://esgf.github.io/esgf-user-support/faq.html which contains contact info for the support list.
